export default [
  { email: 'zerksis@binghamton.edu',
    firstName: 'zerksis',
    lastName: 'umrigar',
  },
  { email: 'umrigar@binghamton.edu',
    firstName: 'zerksis',
    lastName: 'umrigar',
  },
  { email: 'jsmith11@binghamton.edu',
    firstName: 'john',
    lastName: 'smith',
  },
  { email: 'jsmith12@binghamton.edu',
    firstName: 'john',
    lastName: 'smith',
  },
  { email: 'jsmith13@binghamton.edu',
    firstName: 'john',
    lastName: 'smith',
  },
  { email: 'jsmith14@binghamton.edu',
    firstName: 'john',
    lastName: 'smith',
  },
  { email: 'jsmith15@binghamton.edu',
    firstName: 'john',
    lastName: 'smith',
  },
];  


